<?php

namespace Zima\BlogwebBundle\Repository;

use Zima\BlogwebBundle\Entity\Post;
use Zima\BlogwebBundle\Entity\User;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function findUndeletedPost() {
        return $this->createQueryBuilder("a")
            ->where("a.deleted = :false")
            ->setParameter("false", Post::STATUS_DELETED_FALSE)
//            ->andWhere("a.createdAt > :now")
//            ->setParameter("now", new \DateTime())
            ->orderBy("a.createdAt", "DESC")
            ->getQuery()
            ->getResult();
    }
}
